### ISSUE TITLE
Arrows cut off

### ISSUE THREAD

**Issue by BrendonIrwan** [int2str/jssyntaxtree#10]
Draw this tree, and watch the arrow as it vanishes in the middle.

`[A_A [B_B lorem] [C_C [D_D ipsum] [E_E [F_F dolor] [G_G [H_H sit] [I_I [J_J amet] [K_K [L_L consectetur] [M_M [N_N adispicing] [O_O elit -> 1]]]]]]]]`

**Comment by BrendonIrwan** [comment]
I'm working on a patch to fix this if you don't mind.

**Comment by BrendonIrwan** [comment]
I edited `tree.js` to almost-fix this issue.

The arrow-drawing routine is split to the calculation and the actual drawing. That way the intermediate values from said calculation can be used for resizing the canvas prior to drawing the arrows.

Not perfect, but at least the arrows aren't cut-off in most cases anymore.

[tree.zip](https://github.com/int2str/jssyntaxtree/files/5619937/tree.zip)

**Comment by int2str** [comment]
Brendon,

Code looks good. I've committed it on your behalf.
Thanks for helping out - much appreciated!
