### ISSUE TITLE
command-line node.js-compatible approach?

### ISSUE THREAD

**Issue by paul-shannon** [int2str/jssyntaxtree#3]
@int2str  Great to discover your code.  May I ask for a little guidance?

I wish to create syntax trees for Lushootseed, a Pacific Northwest indigenous language.   See, for instance, this work in progress:

  [Mink and Tetyika](http://pshannon.net/sam/minkAndTetyika/)

Does there exist, or can you help me create, a stand-alone javascript script which creates a syntax tree  svg diagram from labeled bracket notation?    With such a capability, I could - from the command line - experiment to find a suitable  bracket notation for each line in the story, of which this is one example:

![image](https://user-images.githubusercontent.com/2480712/67452005-dd881400-f5d6-11e9-8209-b3a01c18025b.png)

After rendering svg to a file, I could later include it as part of the annotation pop-in.

I'll be grateful for any advice you can give.

**Comment by int2str** [comment]
You can launch link to a graph using the URL now, but you'll still get the whole page.
I could potentially add a version or URL parameter that only gives you the graph.

No promises right now, but I'll try.

**Comment by peteruhrig** [comment]
I once hacked together a standalone version of phpsyntaxtree that you can run from the command line. If you are interested, I'll dig in some old archives.

**Comment by paul-shannon** [comment]
Thanks, Peter.  My interest has waned - no need to go to the trouble.  But thank you!

 - Paul

**Comment by int2str** [comment]
Obsolete, based on feedback.
