### ISSUE TITLE
Allow space in nonterminals

### ISSUE THREAD

**Issue by peteruhrig** [int2str/jssyntaxtree#5]
I would like to be able to insert spaces into nonterminals, for instance in the following diagram, where I needed to have a space between "main" and "clause":
[sentence [main-clause [S I] [V admire] [O her reasoning]] but [main-clause [S I] [V reject] [O her conclusions]]]
Of course entering an actual space does not work, and underscores are already taken, but unfortunately, all blank characters I enter will be converted to spaces (e.g. ALT+255 or anything from [here](http://emptycharacter.com/)). I think adding support for something that does not usually occur to be converted into a space would be a useful feature, say a double percent sign:
main%%clause
What do you think?

**Comment by int2str** [comment]
Done. You can use quotes now. So for your example, this would look like this:
["main clause" [S I] [V reject] [O her conclusions]]

**Comment by peteruhrig** [comment]
I am floored. Thank you so much for diving right into that!

**Comment by peteruhrig** [comment]
There is a conflict when combined with manual subscripting:
[sentence [clause [[S:NP [dtm:det Her]
[premod:adj little]
[head:noun sister]]
[V:VP [aux:pv had]
[mv:fv spotted]]
**[O_d: NP [dtm:det the]**
[premod:adj suspicious]
[head:noun van]]
[A:PP [prep from]
["prep. comp.":NP [dtm:det her]
[head:noun hideout]
[postmod:PP [prep in]
["prep. comp.":NP [dtm:det the]
[head:noun tree]]]]]]]]

My actual aim is to display the highlighted line as an O with a subscript d, followed by a non-subscript ":NP". However, if I do this without a space, the ":NP" is subscripted. If I do it with a space, the system creates a new node for the ":NP" part.

**Comment by int2str** [comment]
Bad news on that one... Since I have to draw the sub-script separately "by hand", there is no realistic way to still draw the sub-script and also allow more characters after it. I'd have to do a lot of custom font drawing, and I'm not sure I'm up for it at this point. Sorry.
