### ISSUE TITLE
all words on same level

### ISSUE THREAD

**Issue by peteruhrig** [int2str/jssyntaxtree#6]
Sometimes I would prefer an option that forced jssyntaxtree to put all words on the lowest level. At the moment, I have to cheat and then use a graphics program to correct the line, as in this example:
[sentence [main-clause [S I] [V admire] [O her reasoning]] [[[ but]]] [main-clause [S I] [V reject] [O her conclusions]]]
Thanks for your consideration!

**Comment by int2str** [comment]
Done. Added new option to do this.

**Comment by peteruhrig** [comment]
Excellent, thank you so much!!
