### ISSUE TITLE
Subscripted terms changed behavior

### ISSUE THREAD

**Issue by brucetesar** [int2str/jssyntaxtree#7]
Just saw version 1.10. The arrow feature looks cool! But, indicating subscripts with underscore now acts differently. If I enter [V t_j], I get an error message below the entry box, "Unexpected SUBSCRIPT_PREFIX at idx 3", and the desired subscript does not appear. After playing with it for a while, I found a workaround: [V [t_j]], with an additional pair of square brackets surrounding the subscripted term and its subscript, does what is desired. What seems to matter is that the subscripted term is the first term after a left square bracket: [V [t_j ]] works as expected, as does [V [t_j a]]. Perhaps something to do with how the input is tokenized?

**Comment by int2str** [comment]
Hey Bruce!

Currently, this is working as intended. Subscripts only work on nodes (blue), not leaves (red). The first item after an opening square bracket [ is recognized as a node. This is different (as you found out) from before for sure.

Now, I'm not a linguist, so I'm not sure if my assumptions here are good. Please let me know your thoughts. Is the workaround as you put it acceptable or would you want subscript capability on leaves as well?

Thanks for filing this issue and looking forward to your suggestion.

Cheers,
     Andre

**Comment by int2str** [comment]
Thinking about this more, I don't see a really good reason as to why not allow subscripts on leaf nodes. So, I've implemented this behaviour. So your original example [V t_j] now works again.

Thanks for filing the issue!

**Comment by brucetesar** [comment]
Andre,

thanks for addressing this issue so quickly! I appreciate it, and my students do too. I can’t speak to how other users use it, but in my class, I use subscripts primarily for co-indexing things like traces with their antecedents, and often on the antecedent I put the index on the leaf node itself (especially for head movement). The extra set of square brackets would get the subscript, but it did change the coloring on the trees; the subscripted leaf nodes would be colored as if they were non-leaf nodes. With this correction, my students can once again use jsSyntaxTree to produce trees that look just like the ones in the handouts that I generated months ago.

Thanks again,
Bruce
